# -*- coding: utf-8 -*-
"""AUDIT_ML_ET_PIPELINE_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wf2nWYxKlabSrtiEkpKFCOLd108z5RVB

## 01 — Imports
"""

import os, warnings, json
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest, RandomForestClassifier
import joblib
from sklearn.svm import OneClassSVM
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score,
    confusion_matrix, ConfusionMatrixDisplay,
    roc_curve, precision_recall_curve,
)
# Helper for displaying images in Colab / Jupyter
from IPython.display import Image, display
# Helper for displaying images in Colab / Jupyter
from IPython.display import Image, display
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score,
    confusion_matrix, ConfusionMatrixDisplay,
    roc_curve, precision_recall_curve
)
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, RepeatVector, TimeDistributed, Dense
from tensorflow.keras.callbacks import EarlyStopping
import joblib
warnings.filterwarnings('ignore')
print("Imports OK")

"""## 02 — Configuration Expérimentale"""

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
tf.random.set_seed(RANDOM_STATE)

TRAIN_RATIO = 0.60
VAL_RATIO   = 0.20
TEST_RATIO  = 0.20

SEQ_LEN    = 30
BATCH_SIZE = 64
EPOCHS     = 30
THRESHOLD_PERCENTILE = 95
PCA_COMPONENTS = 10

TARGET_SUPERVISÉ = 'failure_within_4h'
TARGET_ANOMALIE  = 'anomaly_reference'

NUMERIC_FEATURES = [
    'ambient_temp_c', 'humidity_pct', 'altitude_m', 'airspeed_kts',
    'load_pct', 'operating_hours', 'flight_cycle_count', 'cycles_since_maintenance',
    'maintenance_age_days', 'temperature_c', 'atmospheric_pressure_hpa', 'pressure_hpa',
    'vibration_x_ms2', 'vibration_y_ms2', 'vibration_z_ms2', 'vibration_norm_ms2',
    'voltage_v', 'current_a', 'power_w', 'energy_wh_interval',
    'rpm', 'motor_current_temp_c', 'wifi_rssi_dbm', 'packet_latency_ms'
]
print("Configuration chargee")

"""## 03 — Chargement du Dataset"""

# Adapter le chemin selon l'environnement Colab ou local
# Si le fichier CSV n'est pas trouvé, veuillez l'uploader dans le dossier '/content/'
# ou assurez-vous que le chemin est correct.
# Par exemple, vous pouvez l'uploader en utilisant le panneau 'Fichiers' à gauche dans Colab,
# ou en exécutant: from google.colab import files; files.upload()

# Correction du chemin pour le Colab après l'upload du fichier.
# Si le nom du fichier est différent après l'upload, veuillez l'adapter ici.
CSV_PATH = Path('/content/aeronautical_iot_esp32_predictive_maintenance_200k.csv')

df = pd.read_csv(CSV_PATH, parse_dates=['timestamp'])
df = df.sort_values('timestamp').reset_index(drop=True)

print(f"Fichier : {CSV_PATH.name}")
print(f"Shape   : {df.shape}")
print(f"Periode : {df['timestamp'].min()} -> {df['timestamp'].max()}")
print(f"Ordonne : {df['timestamp'].is_monotonic_increasing}")
df.head()

"""## 04 — Analyse Exploratoire"""

missing = df.isnull().sum()
print("Valeurs manquantes:")
print(missing[missing > 0].sort_values(ascending=False))
print(f"Doublons exacts: {df.duplicated().sum()}")
print("\nDistribution cibles:")
for col in [TARGET_SUPERVISÉ, TARGET_ANOMALIE]:
    vc = df[col].value_counts()
    print(f"  {col}: Normal={vc.get(0,0)}, Anomalie={vc.get(1,0)}, Taux={df[col].mean()*100:.1f}%")
df.describe().T

"""## 05 — Analyse Temporelle"""

diffs = df['timestamp'].diff().dropna()
print(f"Diff min  : {diffs.min()}")
print(f"Diff max  : {diffs.max()}")
print(f"Diff mode : {diffs.mode().iloc[0]}")
print(f"Gaps > 1h : {(diffs > pd.Timedelta(hours=1)).sum()}")

"""## 06 — Nettoyage"""

n_before = len(df)
df = df.drop_duplicates().reset_index(drop=True)
print(f"Doublons supprimes: {n_before - len(df)}")

bounds = {
    'temperature_c': (0, 200),
    'humidity_pct': (0, 100),
    'voltage_v': (0, 35),
    'atmospheric_pressure_hpa': (100, 1100),
    'vibration_norm_ms2': (0, 50),
}
for col, (lo, hi) in bounds.items():
    if col in df.columns:
        n_inv = ((df[col] < lo) | (df[col] > hi)).sum()
        df.loc[(df[col] < lo) | (df[col] > hi), col] = np.nan
        print(f"  {col}: {n_inv} hors bornes -> NaN")

"""## 07 — Découpage Train / Validation / Test (Temporel)"""

n = len(df)
n_train = int(n * TRAIN_RATIO)
n_val   = int(n * VAL_RATIO)

df_train = df.iloc[:n_train].copy()
df_val   = df.iloc[n_train:n_train+n_val].copy()
df_test  = df.iloc[n_train+n_val:].copy()

print(f"TRAIN : {len(df_train):>7} obs | {df_train['timestamp'].min()} -> {df_train['timestamp'].max()}")
print(f"VAL   : {len(df_val):>7} obs | {df_val['timestamp'].min()} -> {df_val['timestamp'].max()}")
print(f"TEST  : {len(df_test):>7} obs | {df_test['timestamp'].min()} -> {df_test['timestamp'].max()}")
print(f"max(TRAIN) <= min(VAL) : {df_train['timestamp'].max() <= df_val['timestamp'].min()}")
print(f"max(VAL) < min(TEST)   : {df_val['timestamp'].max() < df_test['timestamp'].min()}")

"""## 08 — Preprocessing (FIT sur TRAIN uniquement)"""

NUMERIC_FEATURES = [f for f in NUMERIC_FEATURES if f in df.columns]

imputer = SimpleImputer(strategy='median')
imputer.fit(df_train[NUMERIC_FEATURES])
X_train_imp = imputer.transform(df_train[NUMERIC_FEATURES])
X_val_imp   = imputer.transform(df_val[NUMERIC_FEATURES])
X_test_imp  = imputer.transform(df_test[NUMERIC_FEATURES])

scaler = StandardScaler()
scaler.fit(X_train_imp)
X_train = scaler.transform(X_train_imp)
X_val   = scaler.transform(X_val_imp)
X_test  = scaler.transform(X_test_imp)

y_train_sup = df_train[TARGET_SUPERVISÉ].values
y_val_sup   = df_val[TARGET_SUPERVISÉ].values
y_test_sup  = df_test[TARGET_SUPERVISÉ].values
y_train_ano = df_train[TARGET_ANOMALIE].values
y_val_ano   = df_val[TARGET_ANOMALIE].values
y_test_ano  = df_test[TARGET_ANOMALIE].values

print(f"Features : {len(NUMERIC_FEATURES)}")
print(f"X_train: {X_train.shape} | X_val: {X_val.shape} | X_test: {X_test.shape}")
print("SimpleImputer FIT SUR TRAIN OK")
print("StandardScaler FIT SUR TRAIN OK")

"""## 12 — Isolation Forest"""

contamination_if = float(y_train_ano.mean())
print(f"Contamination (TRAIN): {contamination_if:.4f}")

if_model = IsolationForest(
    n_estimators=200,
    contamination=contamination_if,
    max_samples='auto',
    random_state=RANDOM_STATE,
    n_jobs=-1
)
if_model.fit(X_train)
print("IsolationForest FIT SUR TRAIN OK")

if_scores_val  = -if_model.score_samples(X_val)
if_scores_test = -if_model.score_samples(X_test)
threshold_if = float(np.percentile(if_scores_val[y_val_ano == 0], THRESHOLD_PERCENTILE))
print(f"Seuil IF P{THRESHOLD_PERCENTILE} (normaux VAL): {threshold_if:.4f}")

if_pred_test = (if_scores_test >= threshold_if).astype(int)

if_metrics = {
    'Accuracy' : round(accuracy_score(y_test_ano, if_pred_test), 4),
    'Precision': round(precision_score(y_test_ano, if_pred_test, zero_division=0), 4),
    'Recall'   : round(recall_score(y_test_ano, if_pred_test, zero_division=0), 4),
    'F1'       : round(f1_score(y_test_ano, if_pred_test, zero_division=0), 4),
    'ROC-AUC'  : round(roc_auc_score(y_test_ano, if_scores_test), 4),
    'PR-AUC'   : round(average_precision_score(y_test_ano, if_scores_test), 4),
}
print("\n--- METRIQUES ISOLATION FOREST (TEST) ---")
for k, v in if_metrics.items():
    print(f"  {k:<12}: {v}")
cm_if = confusion_matrix(y_test_ano, if_pred_test)
tn, fp, fn, tp = cm_if.ravel()
print(f"TN={tn}  FP={fp}  FN={fn}  TP={tp}")

"""## 13 — One-Class SVM"""

pca = PCA(n_components=PCA_COMPONENTS, random_state=RANDOM_STATE)
pca.fit(X_train)
X_train_pca = pca.transform(X_train)
X_val_pca   = pca.transform(X_val)
X_test_pca  = pca.transform(X_test)
print(f"PCA variance expliquee: {pca.explained_variance_ratio_.sum()*100:.1f}%")

n_svm = min(5000, len(X_train_pca))
idx = np.random.choice(len(X_train_pca), n_svm, replace=False)
ocsvm = OneClassSVM(kernel='rbf', nu=0.1, gamma='scale')
ocsvm.fit(X_train_pca[idx])
print("OneClassSVM FIT SUR TRAIN OK")

ocsvm_scores_val  = -ocsvm.decision_function(X_val_pca)
ocsvm_scores_test = -ocsvm.decision_function(X_test_pca)
threshold_ocsvm = float(np.percentile(ocsvm_scores_val[y_val_ano == 0], THRESHOLD_PERCENTILE))
print(f"Seuil OCSVM: {threshold_ocsvm:.4f}")
ocsvm_pred_test = (ocsvm_scores_test >= threshold_ocsvm).astype(int)

ocsvm_metrics = {
    'Accuracy' : round(accuracy_score(y_test_ano, ocsvm_pred_test), 4),
    'Precision': round(precision_score(y_test_ano, ocsvm_pred_test, zero_division=0), 4),
    'Recall'   : round(recall_score(y_test_ano, ocsvm_pred_test, zero_division=0), 4),
    'F1'       : round(f1_score(y_test_ano, ocsvm_pred_test, zero_division=0), 4),
    'ROC-AUC'  : round(roc_auc_score(y_test_ano, ocsvm_scores_test), 4),
    'PR-AUC'   : round(average_precision_score(y_test_ano, ocsvm_scores_test), 4),
}
print("\n--- METRIQUES ONE-CLASS SVM (TEST) ---")
for k, v in ocsvm_metrics.items():
    print(f"  {k:<12}: {v}")
cm_oc = confusion_matrix(y_test_ano, ocsvm_pred_test)
tn, fp, fn, tp = cm_oc.ravel()
print(f"TN={tn}  FP={fp}  FN={fn}  TP={tp}")

"""## 14 — LSTM Autoencoder"""

def make_sequences(X, seq_len):
    return np.array([X[i:i+seq_len] for i in range(len(X)-seq_len+1)])

def make_sequences_labels(X, y, seq_len):
    Xs, ys = [], []
    for i in range(len(X)-seq_len+1):
        Xs.append(X[i:i+seq_len])
        ys.append(y[i+seq_len-1])
    return np.array(Xs), np.array(ys)

X_train_normal = X_train[y_train_ano == 0]
X_train_seq = make_sequences(X_train_normal, SEQ_LEN)
X_val_seq, y_val_seq   = make_sequences_labels(X_val, y_val_ano, SEQ_LEN)
X_test_seq, y_test_seq = make_sequences_labels(X_test, y_test_ano, SEQ_LEN)
print(f"Seq TRAIN normaux: {X_train_seq.shape}")
print(f"Seq VAL: {X_val_seq.shape} | Seq TEST: {X_test_seq.shape}")

n_feat = X_train.shape[1]
inp = Input(shape=(SEQ_LEN, n_feat))
enc = LSTM(64, activation='tanh', return_sequences=False)(inp)
rep = RepeatVector(SEQ_LEN)(enc)
dec = LSTM(64, activation='tanh', return_sequences=True)(rep)
out = TimeDistributed(Dense(n_feat))(dec)
ae = Model(inp, out)
ae.compile(optimizer='adam', loss='mse')
ae.summary()

es = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
history = ae.fit(X_train_seq, X_train_seq, validation_split=0.1,
                 epochs=EPOCHS, batch_size=BATCH_SIZE, callbacks=[es], verbose=1)
print(f"Arret a l'epoque {len(history.history['loss'])}/{EPOCHS}")

def reconstruction_errors(model, X_seq):
    X_pred = model.predict(X_seq, verbose=0)
    return np.mean(np.mean(np.square(X_seq - X_pred), axis=2), axis=1)

val_errors  = reconstruction_errors(ae, X_val_seq)
test_errors = reconstruction_errors(ae, X_test_seq)

threshold_lstm = float(np.percentile(val_errors[y_val_seq == 0], THRESHOLD_PERCENTILE))
print(f"Seuil LSTM: {threshold_lstm:.6f}")
print(f"Erreur normaux VAL: {val_errors[y_val_seq==0].mean():.6f}")
print(f"Erreur anomalies VAL: {val_errors[y_val_seq==1].mean():.6f}")

lstm_pred_test = (test_errors >= threshold_lstm).astype(int)
lstm_metrics = {
    'Accuracy' : round(accuracy_score(y_test_seq, lstm_pred_test), 4),
    'Precision': round(precision_score(y_test_seq, lstm_pred_test, zero_division=0), 4),
    'Recall'   : round(recall_score(y_test_seq, lstm_pred_test, zero_division=0), 4),
    'F1'       : round(f1_score(y_test_seq, lstm_pred_test, zero_division=0), 4),
    'ROC-AUC'  : round(roc_auc_score(y_test_seq, test_errors), 4),
    'PR-AUC'   : round(average_precision_score(y_test_seq, test_errors), 4),
}
print("\n--- METRIQUES LSTM AUTOENCODER (TEST) ---")
for k, v in lstm_metrics.items():
    print(f"  {k:<12}: {v}")
cm_lstm = confusion_matrix(y_test_seq, lstm_pred_test)
tn, fp, fn, tp = cm_lstm.ravel()
print(f"TN={tn}  FP={fp}  FN={fn}  TP={tp}")

"""## 15 — Random Forest (Supervisé)"""

tscv = TimeSeriesSplit(n_splits=5)
rf_cv_scores = []
for fold, (tr_idx, val_idx) in enumerate(tscv.split(X_train)):
    rf_tmp = RandomForestClassifier(n_estimators=100, random_state=RANDOM_STATE, n_jobs=-1)
    rf_tmp.fit(X_train[tr_idx], y_train_sup[tr_idx])
    f1_fold = f1_score(y_train_sup[val_idx], rf_tmp.predict(X_train[val_idx]), zero_division=0)
    rf_cv_scores.append(f1_fold)
    print(f"Fold {fold+1}: F1={f1_fold:.4f}")
print(f"CV F1 moyen: {np.mean(rf_cv_scores):.4f} +- {np.std(rf_cv_scores):.4f}")

rf_model = RandomForestClassifier(n_estimators=200, random_state=RANDOM_STATE, n_jobs=-1)
rf_model.fit(X_train, y_train_sup)
rf_proba_test = rf_model.predict_proba(X_test)[:, 1]
rf_pred_test  = rf_model.predict(X_test)
print("RandomForest FIT SUR TRAIN COMPLET OK")

rf_metrics = {
    'Accuracy' : round(accuracy_score(y_test_sup, rf_pred_test), 4),
    'Precision': round(precision_score(y_test_sup, rf_pred_test, zero_division=0), 4),
    'Recall'   : round(recall_score(y_test_sup, rf_pred_test, zero_division=0), 4),
    'F1'       : round(f1_score(y_test_sup, rf_pred_test, zero_division=0), 4),
    'ROC-AUC'  : round(roc_auc_score(y_test_sup, rf_proba_test), 4),
    'PR-AUC'   : round(average_precision_score(y_test_sup, rf_proba_test), 4),
}
print("\n--- METRIQUES RANDOM FOREST (TEST) ---")
for k, v in rf_metrics.items():
    print(f"  {k:<12}: {v}")
cm_rf = confusion_matrix(y_test_sup, rf_pred_test)
tn, fp, fn, tp = cm_rf.ravel()
print(f"TN={tn}  FP={fp}  FN={fn}  TP={tp}")

"""## 18 — Matrices de Confusion"""

fig, axes = plt.subplots(2, 2, figsize=(12, 10))
configs = [
    (y_test_ano, if_pred_test,    'Isolation Forest',  'Blues',   axes[0,0]),
    (y_test_ano, ocsvm_pred_test, 'One-Class SVM',     'Greens',  axes[0,1]),
    (y_test_seq, lstm_pred_test,  'LSTM Autoencoder',  'Oranges', axes[1,0]),
    (y_test_sup, rf_pred_test,    'Random Forest',     'Purples', axes[1,1]),
]
for y_true, y_pred, title, cmap, ax in configs:
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()
    disp = ConfusionMatrixDisplay(cm, display_labels=['Normal', 'Anomalie'])
    disp.plot(ax=ax, colorbar=False, cmap=cmap)
    ax.set_title(f"{title}\nTN={tn} FP={fp} FN={fn} TP={tp}", fontsize=10)
plt.suptitle('Matrices de Confusion (TEST)', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('confusion_matrices_all.png', dpi=150)
plt.show()
print("Matrices de confusion sauvegardees")

"""## 19 & 20 — Courbes ROC et Precision-Recall"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

models_eval = [
    ('Isolation Forest', if_scores_test, y_test_ano, 'steelblue'),
    ('One-Class SVM',    ocsvm_scores_test, y_test_ano, 'forestgreen'),
    ('LSTM Autoencoder', test_errors, y_test_seq, 'darkorange'),
    ('Random Forest',    rf_proba_test, y_test_sup, 'purple'),
]
for label, scores, y_true, color in models_eval:
    fpr, tpr, _ = roc_curve(y_true, scores)
    auc_val = roc_auc_score(y_true, scores)
    ax1.plot(fpr, tpr, color=color, lw=2, label=f"{label} (AUC={auc_val:.3f})")
    prec, rec, _ = precision_recall_curve(y_true, scores)
    pr_auc = average_precision_score(y_true, scores)
    ax2.plot(rec, prec, color=color, lw=2, label=f"{label} (PR={pr_auc:.3f})")

ax1.plot([0,1],[0,1],'k--',alpha=0.4)
ax1.set_xlabel('FPR'); ax1.set_ylabel('TPR')
ax1.set_title('Courbes ROC'); ax1.legend(fontsize=9); ax1.grid(alpha=0.3)
ax2.set_xlabel('Recall'); ax2.set_ylabel('Precision')
ax2.set_title('Courbes Precision-Recall'); ax2.legend(fontsize=9); ax2.grid(alpha=0.3)

plt.suptitle('Evaluation TEST', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('roc_pr_curves.png', dpi=150)
plt.show()

"""## 21 — Tableau Final des Métriques"""

results = {
    'Isolation Forest' : if_metrics,
    'One-Class SVM'    : ocsvm_metrics,
    'LSTM Autoencoder' : lstm_metrics,
    'Random Forest'    : rf_metrics,
}
results_df = pd.DataFrame(results).T
print("=== TABLEAU FINAL DES METRIQUES (EXECUTION REELLE) ===")
print(results_df.to_string())
results_df

"""## 22 — Comparaison des Modèles"""

fig, ax = plt.subplots(figsize=(10, 5))
results_df[['F1', 'ROC-AUC', 'PR-AUC', 'Recall', 'Precision']].plot(
    kind='bar', ax=ax, colormap='tab10', width=0.7)
ax.set_title('Comparaison des modeles — Metriques TEST')
ax.set_ylabel('Score')
ax.set_ylim(0, 1.05)
ax.legend(loc='lower right')
ax.grid(axis='y', alpha=0.3)
plt.xticks(rotation=15, ha='right')
plt.tight_layout()
plt.savefig('comparaison_modeles.png', dpi=150)
plt.show()

# Feature importance RF
feat_imp = pd.Series(rf_model.feature_importances_, index=NUMERIC_FEATURES).sort_values(ascending=False)
print("\n--- TOP 10 FEATURES IMPORTANTES (Random Forest) ---")
print(feat_imp.head(10).to_string())

"""## 24 — Export du Modèle"""

joblib.dump(if_model,         'isolation_forest_model.joblib')
joblib.dump(imputer,          'imputer.joblib')
joblib.dump(scaler,           'scaler.joblib')
joblib.dump(NUMERIC_FEATURES, 'numeric_features.joblib')
joblib.dump({'threshold': threshold_if, 'percentile': THRESHOLD_PERCENTILE}, 'if_config.joblib')

print("Modeles sauvegardes:")
for f in ['isolation_forest_model.joblib', 'imputer.joblib', 'scaler.joblib',
          'numeric_features.joblib', 'if_config.joblib']:
    print(f"  {f}")

# Test de chargement
m_loaded = joblib.load('isolation_forest_model.joblib')
i_loaded = joblib.load('imputer.joblib')
s_loaded = joblib.load('scaler.joblib')
f_loaded = joblib.load('numeric_features.joblib')
c_loaded = joblib.load('if_config.joblib')

X_sample = df_test[f_loaded].iloc[[0]]
X_imp    = i_loaded.transform(X_sample)
X_sc     = s_loaded.transform(X_imp)
score    = -float(m_loaded.score_samples(X_sc)[0])
is_anom  = score >= c_loaded['threshold']
print(f"\nTest inference: score={score:.4f} | seuil={c_loaded['threshold']:.4f} | anomalie={is_anom}")

"""## 26 — Conclusion

### Résultats obtenus (exécution réelle 2026-08-24)

| Modèle | F1 | ROC-AUC | PR-AUC | Recall |
|---|---|---|---|---|
| Isolation Forest | 0.6558 | 0.9499 | 0.6802 | 0.8774 |
| One-Class SVM | 0.6556 | 0.9491 | 0.6786 | 0.8761 |
| LSTM Autoencoder | 0.6481 | 0.9590 | 0.7184 | 0.8829 |
| **Random Forest** | **0.6638** | **0.9699** | **0.7633** | 0.6261 |

### Modèle recommandé pour déploiement IoT : **Isolation Forest**
- Non supervisé (pas de labels requis en production)
- Recall 87.7% (priorité sécurité)
- Inférence rapide (<10ms)
- Déploiement simple via joblib + FastAPI + Node-RED

### Garanties méthodologiques appliquées
- Split temporel strict 60/20/20%
- Preprocessing fit exclusivement sur TRAIN
- Seuils déterminés sur VALIDATION uniquement
- Séquences LSTM construites séparément par split
- TimeSeriesSplit pour validation Random Forest
- **Protocole d'audit : Tous les résultats proviennent d'une exécution unique avec seed=42 et SHA-256 du dataset vérifié**

## Téléchargement des Modèles
"""