services:
  - type: web
    name: iot-anomaly-pfe
    runtime: python
    rootDir: api-ml-backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app_flask.py
    plan: free
    region: frankfurt
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
