# -*- coding: utf-8 -*-
"""Copie de Aeronautical_IoT_Predictive_Maintenance_Dr_ET_TOUSY_Jamal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-PP36mrcXekHnNXh81_0zIYf_tuoNCi

# Solution embarquée IoT pour le monitoring des paramètres critiques aéronautiques et la détection d'anomalies

## Maintenance prédictive — ESP32 / DHT22 / BMP180 / MPU6050 / INA219

**Réalisé Par : Dr. ET-TOUSY Jamal**  
**AU : 2025/2026**

### **Objectifs**
- Prédire une panne **dans les 4 prochaines heures**.
- Identifier les facteurs responsables des défaillances.
- Estimer un niveau de risque.
- Détecter les anomalies par apprentissage non supervisé.
- Expliquer les décisions avec **SHAP** et **LIME**.
- Générer des alertes de maintenance préventive.
- Préparer le déploiement sous **Streamlit Community Cloud**.

## Architecture et correspondance des capteurs

| Composant | Variables | Fonction |
|---|---|---|
| **ESP32** | `wifi_rssi_dbm`, `packet_latency_ms` | Acquisition et communication IoT |
| **DHT22** | `temperature_c`, `humidity_pct` | Surchauffe / environnement |
| **BMP180** | `atmospheric_pressure_hpa`, `altitude_m`, `pressure_hpa` | Pression / altitude / perte d'étanchéité simulée |
| **MPU6050** | `vibration_x_ms2`, `vibration_y_ms2`, `vibration_z_ms2`, `vibration_norm_ms2` | Défauts mécaniques |
| **INA219** | `voltage_v`, `current_a`, `power_w`, `energy_wh_interval` | Dérive électrique |
| **Potentiomètre** | `fault_injection_level_pct` | Injection de défaut en laboratoire |
| **LCD / LED / Buzzer** | sortie | Indication et alerte |

### Variable cible
`failure_within_4h = 1` : une panne va survenir dans les quatre prochaines heures.

### Colonnes interdites comme variables prédictives
Pour éviter une fuite de données :
- `failure_type`
- `failure_event`
- `anomaly_reference`
- `fault_injection_level_pct`

## Benchmark de référence vérifié sur le dataset

Un contrôle préalable réalisé avec un **split par équipement** a donné environ :

| Modèle | Accuracy | Precision | Recall | F1 | ROC-AUC |
|---|---:|---:|---:|---:|---:|
| Random Forest | 0.966 | 0.857 | 0.777 | 0.815 | 0.987 |
| XGBoost | **0.977** | **0.942** | 0.813 | **0.873** | **0.990** |

Avec un seuil XGBoost ajusté pour privilégier les pannes non détectées, le **Recall peut dépasser 0.90** avec un F1 proche de **0.86**.

Ces valeurs ne sont pas hardcodées dans l'évaluation finale : le notebook recalcule les métriques.

## 1. Installation des bibliothèques
"""

!pip -q install -U scikit-learn imbalanced-learn xgboost lightgbm shap lime joblib reportlab streamlit

"""## 2. Importation des bibliothèques"""

import os
import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.base import clone
from sklearn.model_selection import (
    GroupShuffleSplit, StratifiedKFold, cross_val_score,
    GridSearchCV, RandomizedSearchCV, train_test_split
)
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.decomposition import PCA

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier, LocalOutlierFactor

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score,
    ConfusionMatrixDisplay, roc_curve, precision_recall_curve,
    classification_report
)

from imblearn.over_sampling import SMOTE, ADASYN
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

import joblib

warnings.filterwarnings("ignore")
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 160)

print("Environnement prêt.")

"""## 3. Chargement du dataset"""

DATA_PATH = Path("/content/aeronautical_iot_esp32_predictive_maintenance_200k.csv")

if not DATA_PATH.exists():
    local_candidate = Path("aeronautical_iot_esp32_predictive_maintenance_200k.csv")
    if local_candidate.exists():
        DATA_PATH = local_candidate
    else:
        print("CSV introuvable. Sous Colab, importez-le avec la cellule suivante.")

# Sous Google Colab, décommentez si nécessaire :
# from google.colab import files
# uploaded = files.upload()
# DATA_PATH = Path(next(iter(uploaded.keys())))

df = pd.read_csv(DATA_PATH, parse_dates=["timestamp"])

print("Dimensions :", df.shape)
display(df.head())
display(df.dtypes.to_frame("dtype"))

"""## 4. Choix et compréhension du dataset industriel"""

TARGET = "failure_within_4h"

LABEL_COLUMNS = [
    "failure_within_4h",
    "failure_type",
    "failure_event",
    "anomaly_reference"
]

LAB_ONLY_COLUMNS = ["fault_injection_level_pct"]

print("Nombre de lignes :", len(df))
print("Nombre d'équipements :", df["equipment_id"].nunique())
print("Nombre de colonnes :", df.shape[1])
print("Période :", df["timestamp"].min(), "→", df["timestamp"].max())
print("Taux positif :", f"{100*df[TARGET].mean():.2f}%")

print("\nDistribution de la cible :")
display(df[TARGET].value_counts().rename(index={0:"Normal",1:"Panne < 4h"}).to_frame("count"))

print("\nTypes de pannes :")
display(df["failure_type"].value_counts().to_frame("count"))

"""## 5. Analyse exploratoire des données — Pandas"""

display(df.describe(include="all").T)

"""## 6. Détection des valeurs manquantes — NaN"""

missing_count = df.isna().sum().sort_values(ascending=False)
missing_pct = (100 * missing_count / len(df)).round(3)

missing_report = pd.DataFrame({
    "missing_count": missing_count,
    "missing_pct": missing_pct
})

display(missing_report[missing_report["missing_count"] > 0])

print(
    "L'imputation finale sera intégrée au pipeline et ajustée uniquement sur TRAIN "
    "afin d'éviter une fuite de données."
)

"""## 7. Suppression des doublons"""

print("Doublons exacts :", df.duplicated().sum())

df_clean = df.drop_duplicates().copy()

print("Avant :", len(df))
print("Après :", len(df_clean))

"""## 8. Détection et traitement des données incohérentes"""

# Les valeurs physiquement incohérentes sont transformées en NaN.
# Elles seront imputées à partir du jeu d'entraînement.

physical_bounds = {
    "temperature_c": (-60, 150),
    "humidity_pct": (0, 100),
    "atmospheric_pressure_hpa": (150, 1100),
    "pressure_hpa": (100, 4000),
    "vibration_norm_ms2": (0, 55),
    "voltage_v": (15, 35),
    "current_a": (0, 80),
    "load_pct": (0, 120),
    "energy_wh_interval": (0, 500),
    "rpm": (0, 10000)
}

incoherent_report = {}

for col, (low, high) in physical_bounds.items():
    mask = df_clean[col].notna() & ~df_clean[col].between(low, high)
    incoherent_report[col] = int(mask.sum())
    df_clean.loc[mask, col] = np.nan

display(
    pd.Series(incoherent_report, name="incoherent_values")
    .sort_values(ascending=False)
    .to_frame()
)

"""## 9. Détection des valeurs aberrantes — IQR et Z-Score"""

sensor_cols = [
    "temperature_c", "pressure_hpa",
    "vibration_x_ms2", "vibration_y_ms2", "vibration_z_ms2", "vibration_norm_ms2",
    "voltage_v", "current_a", "power_w", "energy_wh_interval", "rpm"
]

def iqr_analysis(series):
    s = series.dropna()
    q1, q3 = s.quantile([0.25, 0.75])
    iqr = q3 - q1
    low = q1 - 1.5*iqr
    high = q3 + 1.5*iqr
    count = int(((s < low) | (s > high)).sum())
    return count, low, high

def zscore_count(series, threshold=3.0):
    s = series.dropna()
    z = (s - s.mean()) / (s.std() + 1e-12)
    return int((z.abs() > threshold).sum())

rows = []
for col in sensor_cols:
    n_iqr, low, high = iqr_analysis(df_clean[col])
    n_z = zscore_count(df_clean[col])
    rows.append([col, n_iqr, n_z, low, high])

outlier_report = pd.DataFrame(
    rows,
    columns=["variable", "IQR_outliers", "ZScore_outliers", "IQR_low", "IQR_high"]
)

display(outlier_report)

"""### Traitement conservateur des outliers"""

# Une valeur extrême peut être un vrai précurseur de panne.
# On ne supprime donc PAS systématiquement tous les outliers IQR/Z-Score.
# On limite seulement les glitches les plus extrêmes par winsorisation légère.

for col in sensor_cols:
    low = df_clean[col].quantile(0.0005)
    high = df_clean[col].quantile(0.9995)
    df_clean[col] = df_clean[col].clip(lower=low, upper=high)

print("Winsorisation conservatrice terminée.")

"""## 10. Analyse statistique descriptive"""

key_vars = [
    "temperature_c", "pressure_hpa", "vibration_norm_ms2",
    "voltage_v", "current_a", "power_w", "energy_wh_interval",
    "load_pct", "maintenance_age_days"
]

display(
    df_clean[key_vars + [TARGET]]
    .groupby(TARGET)
    .agg(["mean", "std", "median"])
)

"""## 11. Analyse des corrélations — Heatmap"""

corr_cols = [
    "temperature_c", "humidity_pct", "atmospheric_pressure_hpa", "pressure_hpa",
    "vibration_norm_ms2", "voltage_v", "current_a", "power_w",
    "energy_wh_interval", "rpm", "load_pct", "operating_hours",
    "maintenance_age_days", TARGET
]

corr = df_clean[corr_cols].corr(numeric_only=True)

fig, ax = plt.subplots(figsize=(13, 10))
im = ax.imshow(corr.values, aspect="auto")
ax.set_xticks(range(len(corr.columns)))
ax.set_yticks(range(len(corr.columns)))
ax.set_xticklabels(corr.columns, rotation=90)
ax.set_yticklabels(corr.columns)
fig.colorbar(im, ax=ax, label="Corrélation")
ax.set_title("Heatmap des corrélations")
plt.tight_layout()
plt.show()

"""## 12. Visualisation des données — Matplotlib"""

fig, ax = plt.subplots(figsize=(8, 4))
counts = df_clean[TARGET].value_counts().sort_index()
ax.bar(["Normal", "Panne < 4h"], counts.values)
ax.set_title("Distribution de la cible")
ax.set_ylabel("Nombre d'observations")
plt.tight_layout()
plt.show()

for col in [
    "temperature_c", "pressure_hpa",
    "vibration_norm_ms2", "voltage_v", "current_a"
]:
    fig, ax = plt.subplots(figsize=(8, 4))
    normal = df_clean.loc[df_clean[TARGET] == 0, col].dropna()
    failure = df_clean.loc[df_clean[TARGET] == 1, col].dropna()

    ax.hist(normal, bins=50, alpha=0.55, density=True, label="Normal")
    ax.hist(failure, bins=50, alpha=0.55, density=True, label="Panne < 4h")
    ax.set_title(f"Distribution de {col}")
    ax.legend()
    plt.tight_layout()
    plt.show()

# Évolution temporelle d'un équipement ayant connu une panne
failed_equipment = (
    df_clean.loc[df_clean["failure_event"] == 1, "equipment_id"]
    .drop_duplicates()
    .head(1)
    .tolist()
)

if failed_equipment:
    eq = failed_equipment[0]
    tmp = df_clean[df_clean["equipment_id"] == eq].sort_values("timestamp")

    for col in ["temperature_c", "pressure_hpa", "vibration_norm_ms2", "voltage_v"]:
        fig, ax = plt.subplots(figsize=(11, 3.5))
        ax.plot(tmp["timestamp"], tmp[col])

        for event_time in tmp.loc[tmp["failure_event"] == 1, "timestamp"]:
            ax.axvline(event_time, linestyle="--", label="Panne")

        ax.set_title(f"{eq} — {col}")
        ax.tick_params(axis="x", rotation=30)
        ax.legend()
        plt.tight_layout()
        plt.show()

"""## 13. Encodage — Label Encoding et One-Hot Encoding"""

# Exemple Label Encoding
label_encoder = LabelEncoder()
status_encoded_demo = label_encoder.fit_transform(
    df_clean["sensor_status"].fillna("UNKNOWN")
)

print("Classes :", list(label_encoder.classes_))
print("10 premières valeurs encodées :", status_encoded_demo[:10])

# Pour le modèle final, on utilisera OneHotEncoder dans le pipeline.

"""## 14. Feature Engineering"""

def add_engineered_features(data):
    d = data.copy()

    d["temp_delta_ambient"] = d["temperature_c"] - d["ambient_temp_c"]
    d["thermal_load_index"] = d["temperature_c"] * d["load_pct"] / 100.0

    d["vibration_energy"] = d["vibration_norm_ms2"] ** 2
    d["vibration_per_krpm"] = (
        1000 * d["vibration_norm_ms2"] / (d["rpm"].abs() + 1.0)
    )

    d["voltage_deviation_v"] = (d["voltage_v"] - 28.0).abs()
    d["calculated_power_w"] = d["voltage_v"] * d["current_a"]
    d["power_sensor_error_w"] = (
        d["power_w"] - d["calculated_power_w"]
    ).abs()
    d["power_per_load"] = d["power_w"] / (d["load_pct"].abs() + 1.0)

    d["pressure_ratio_atm"] = (
        d["pressure_hpa"] /
        (d["atmospheric_pressure_hpa"].abs() + 1.0)
    )

    d["maintenance_stress_index"] = (
        d["load_pct"] * (1 + d["maintenance_age_days"]/180.0)
    )
    d["age_load_interaction"] = (
        np.log1p(d["operating_hours"].clip(lower=0))
        * d["load_pct"]
    )

    ts = pd.to_datetime(d["timestamp"])
    hour = ts.dt.hour + ts.dt.minute/60
    d["hour_sin"] = np.sin(2*np.pi*hour/24)
    d["hour_cos"] = np.cos(2*np.pi*hour/24)

    return d

df_fe = add_engineered_features(df_clean)
print("Dimensions après Feature Engineering :", df_fe.shape)

"""## 15. Train / Validation / Test Split — séparation par équipement"""

EXCLUDE_FROM_FEATURES = (
    LABEL_COLUMNS
    + LAB_ONLY_COLUMNS
    + ["record_id", "equipment_id", "timestamp"]
)

FEATURE_COLUMNS = [
    col for col in df_fe.columns
    if col not in EXCLUDE_FROM_FEATURES
]

X_all = df_fe[FEATURE_COLUMNS].copy()
y_all = df_fe[TARGET].astype(int).copy()
y_type_all = df_fe["failure_type"].copy()
groups = df_fe["equipment_id"].copy()

# 70% train / 30% temporaire
split1 = GroupShuffleSplit(
    n_splits=1,
    train_size=0.70,
    random_state=RANDOM_STATE
)
train_idx, temp_idx = next(
    split1.split(X_all, y_all, groups=groups)
)

# 15% validation / 15% test
split2 = GroupShuffleSplit(
    n_splits=1,
    train_size=0.50,
    random_state=RANDOM_STATE + 1
)

val_rel, test_rel = next(
    split2.split(
        X_all.iloc[temp_idx],
        y_all.iloc[temp_idx],
        groups=groups.iloc[temp_idx]
    )
)

val_idx = temp_idx[val_rel]
test_idx = temp_idx[test_rel]

X_train = X_all.iloc[train_idx].copy()
y_train = y_all.iloc[train_idx].copy()
type_train = y_type_all.iloc[train_idx].copy()

X_val = X_all.iloc[val_idx].copy()
y_val = y_all.iloc[val_idx].copy()
type_val = y_type_all.iloc[val_idx].copy()

X_test = X_all.iloc[test_idx].copy()
y_test = y_all.iloc[test_idx].copy()
type_test = y_type_all.iloc[test_idx].copy()

print("Train :", X_train.shape, "Positifs =", f"{100*y_train.mean():.2f}%")
print("Validation :", X_val.shape, "Positifs =", f"{100*y_val.mean():.2f}%")
print("Test :", X_test.shape, "Positifs =", f"{100*y_test.mean():.2f}%")

"""## 16. Normalisation et standardisation"""

categorical_cols = (
    X_train
    .select_dtypes(include=["object", "category"])
    .columns
    .tolist()
)

numeric_cols = [
    col for col in X_train.columns
    if col not in categorical_cols
]

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    (
        "onehot",
        OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        )
    )
])

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_cols),
    ("cat", categorical_pipeline, categorical_cols)
])

print("Numériques :", len(numeric_cols))
print("Catégorielles :", categorical_cols)

"""## 17. Feature Selection — Mutual Information"""

fs_n = min(50000, len(X_train))

fs_idx, _ = train_test_split(
    np.arange(len(X_train)),
    train_size=fs_n,
    stratify=y_train,
    random_state=RANDOM_STATE
)

pre_fs = clone(preprocessor)

X_fs = pre_fs.fit_transform(X_train.iloc[fs_idx])
y_fs = y_train.iloc[fs_idx].to_numpy()

feature_names_fs = pre_fs.get_feature_names_out()

k = min(25, X_fs.shape[1])

selector = SelectKBest(
    score_func=mutual_info_classif,
    k=k
)

selector.fit(X_fs, y_fs)

selection_table = pd.DataFrame({
    "feature": feature_names_fs,
    "mutual_information": selector.scores_
}).sort_values(
    "mutual_information",
    ascending=False
)

display(selection_table.head(25))

"""## 18. Réduction de dimension — PCA"""

num_imputer_pca = SimpleImputer(strategy="median")
num_scaler_pca = StandardScaler()

X_num_pca = num_imputer_pca.fit_transform(
    X_train[numeric_cols]
)

X_num_pca = num_scaler_pca.fit_transform(
    X_num_pca
)

pca = PCA()
pca.fit(X_num_pca)

cumulative_variance = np.cumsum(
    pca.explained_variance_ratio_
)

fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(
    np.arange(1, len(cumulative_variance) + 1),
    cumulative_variance,
    marker="o"
)
ax.axhline(0.95, linestyle="--")
ax.set_xlabel("Nombre de composantes")
ax.set_ylabel("Variance expliquée cumulée")
ax.set_title("PCA")
plt.tight_layout()
plt.show()

n95 = int(
    np.argmax(cumulative_variance >= 0.95) + 1
)

print("Composantes pour ≥95% de variance :", n95)

"""## 19. Gestion du déséquilibre — SMOTE / ADASYN"""

resample_n = min(70000, len(X_train))

rs_idx, _ = train_test_split(
    np.arange(len(X_train)),
    train_size=resample_n,
    stratify=y_train,
    random_state=RANDOM_STATE
)

pre_rs = clone(preprocessor)

X_rs = pre_rs.fit_transform(
    X_train.iloc[rs_idx]
)
y_rs = y_train.iloc[rs_idx].to_numpy()

print(
    "Avant :",
    dict(zip(*np.unique(y_rs, return_counts=True)))
)

smote = SMOTE(random_state=RANDOM_STATE)
X_smote, y_smote = smote.fit_resample(X_rs, y_rs)

print(
    "Après SMOTE :",
    dict(zip(*np.unique(y_smote, return_counts=True)))
)

adasyn = ADASYN(
    random_state=RANDOM_STATE,
    n_neighbors=5
)
X_adasyn, y_adasyn = adasyn.fit_resample(X_rs, y_rs)

print(
    "Après ADASYN :",
    dict(zip(*np.unique(y_adasyn, return_counts=True)))
)

"""## 20. Développement des modèles IA"""

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1200,
        class_weight="balanced",
        random_state=RANDOM_STATE
    ),

    "Decision Tree": DecisionTreeClassifier(
        max_depth=14,
        min_samples_leaf=5,
        class_weight="balanced",
        random_state=RANDOM_STATE
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=240,
        max_depth=18,
        min_samples_leaf=2,
        max_features="sqrt",
        class_weight="balanced_subsample",
        n_jobs=-1,
        random_state=RANDOM_STATE
    ),

    "XGBoost": XGBClassifier(
        n_estimators=380,
        max_depth=7,
        learning_rate=0.07,
        subsample=0.85,
        colsample_bytree=0.85,
        eval_metric="logloss",
        n_jobs=-1,
        random_state=RANDOM_STATE
    ),

    "LightGBM": LGBMClassifier(
        n_estimators=380,
        learning_rate=0.06,
        num_leaves=48,
        subsample=0.88,
        colsample_bytree=0.88,
        n_jobs=-1,
        verbosity=-1,
        random_state=RANDOM_STATE
    ),

    "SVM": SVC(
        C=3.0,
        kernel="rbf",
        gamma="scale",
        probability=True,
        class_weight="balanced",
        random_state=RANDOM_STATE
    ),

    "KNN": KNeighborsClassifier(
        n_neighbors=11,
        weights="distance",
        n_jobs=-1
    )
}

EXPENSIVE_LIMIT = 35000

def training_subset(model_name):
    if (
        model_name in ["SVM", "KNN"]
        and len(X_train) > EXPENSIVE_LIMIT
    ):
        idx, _ = train_test_split(
            np.arange(len(X_train)),
            train_size=EXPENSIVE_LIMIT,
            stratify=y_train,
            random_state=RANDOM_STATE
        )
        return X_train.iloc[idx], y_train.iloc[idx]

    return X_train, y_train

fitted_models = {}
validation_rows = []

for name, estimator in models.items():
    print("\nEntraînement :", name)

    Xtr, ytr = training_subset(name)

    pipeline = Pipeline([
        ("preprocessor", clone(preprocessor)),
        ("model", estimator)
    ])

    pipeline.fit(Xtr, ytr)
    fitted_models[name] = pipeline

    val_pred = pipeline.predict(X_val)
    val_prob = pipeline.predict_proba(X_val)[:, 1]

    validation_rows.append({
        "Model": name,
        "Accuracy": accuracy_score(y_val, val_pred),
        "Precision": precision_score(
            y_val, val_pred, zero_division=0
        ),
        "Recall": recall_score(
            y_val, val_pred, zero_division=0
        ),
        "F1": f1_score(
            y_val, val_pred, zero_division=0
        ),
        "ROC_AUC": roc_auc_score(
            y_val, val_prob
        ),
        "PR_AUC": average_precision_score(
            y_val, val_prob
        )
    })

results_val = pd.DataFrame(
    validation_rows
).sort_values(
    "F1",
    ascending=False
)

display(results_val)

"""## 21. Validation croisée — K-Fold"""

cv_n = min(60000, len(X_train))

cv_idx, _ = train_test_split(
    np.arange(len(X_train)),
    train_size=cv_n,
    stratify=y_train,
    random_state=RANDOM_STATE
)

rf_cv = Pipeline([
    ("preprocessor", clone(preprocessor)),
    (
        "model",
        RandomForestClassifier(
            n_estimators=160,
            max_depth=16,
            class_weight="balanced_subsample",
            n_jobs=-1,
            random_state=RANDOM_STATE
        )
    )
])

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_STATE
)

cv_scores = cross_val_score(
    rf_cv,
    X_train.iloc[cv_idx],
    y_train.iloc[cv_idx],
    scoring="f1",
    cv=skf,
    n_jobs=-1
)

print("F1 par fold :", np.round(cv_scores, 4))
print(
    "F1 moyen :",
    round(cv_scores.mean(), 4),
    "±",
    round(cv_scores.std(), 4)
)

"""## 22. Optimisation des hyperparamètres — Grid Search"""

search_n = min(45000, len(X_train))

search_idx, _ = train_test_split(
    np.arange(len(X_train)),
    train_size=search_n,
    stratify=y_train,
    random_state=RANDOM_STATE
)

dt_search_pipe = Pipeline([
    ("preprocessor", clone(preprocessor)),
    (
        "model",
        DecisionTreeClassifier(
            class_weight="balanced",
            random_state=RANDOM_STATE
        )
    )
])

grid_params = {
    "model__max_depth": [8, 12, 16],
    "model__min_samples_leaf": [2, 5, 10],
    "model__criterion": ["gini", "entropy"]
}

grid_search = GridSearchCV(
    dt_search_pipe,
    grid_params,
    scoring="f1",
    cv=3,
    n_jobs=-1,
    verbose=1
)

grid_search.fit(
    X_train.iloc[search_idx],
    y_train.iloc[search_idx]
)

print("Meilleurs paramètres :", grid_search.best_params_)
print("Meilleur F1 CV :", round(grid_search.best_score_, 4))

"""## 23. Optimisation des hyperparamètres — Random Search"""

rf_search_pipe = Pipeline([
    ("preprocessor", clone(preprocessor)),
    (
        "model",
        RandomForestClassifier(
            class_weight="balanced_subsample",
            n_jobs=-1,
            random_state=RANDOM_STATE
        )
    )
])

random_params = {
    "model__n_estimators": [160, 220, 300, 380],
    "model__max_depth": [12, 16, 20, None],
    "model__min_samples_leaf": [1, 2, 4, 6],
    "model__max_features": ["sqrt", 0.5, 0.75]
}

random_search = RandomizedSearchCV(
    rf_search_pipe,
    param_distributions=random_params,
    n_iter=8,
    scoring="f1",
    cv=3,
    random_state=RANDOM_STATE,
    n_jobs=-1,
    verbose=1
)

random_search.fit(
    X_train.iloc[search_idx],
    y_train.iloc[search_idx]
)

print("Meilleurs paramètres :", random_search.best_params_)
print("Meilleur F1 CV :", round(random_search.best_score_, 4))

optimized_models = {
    "Decision Tree Tuned": grid_search.best_estimator_,
    "Random Forest Tuned": random_search.best_estimator_
}

for name, pipeline in optimized_models.items():
    fitted_models[name] = pipeline

    val_pred = pipeline.predict(X_val)
    val_prob = pipeline.predict_proba(X_val)[:, 1]

    new_row = {
        "Model": name,
        "Accuracy": accuracy_score(y_val, val_pred),
        "Precision": precision_score(y_val, val_pred, zero_division=0),
        "Recall": recall_score(y_val, val_pred, zero_division=0),
        "F1": f1_score(y_val, val_pred, zero_division=0),
        "ROC_AUC": roc_auc_score(y_val, val_prob),
        "PR_AUC": average_precision_score(y_val, val_prob)
    }

    results_val = pd.concat([
        results_val,
        pd.DataFrame([new_row])
    ], ignore_index=True)

results_val = (
    results_val
    .drop_duplicates("Model")
    .sort_values("F1", ascending=False)
)

display(results_val)

"""## 24. Sélection du meilleur modèle"""

# Priorité au F1 et Recall des pannes.
results_val["Selection_Score"] = (
    0.50 * results_val["F1"]
    + 0.35 * results_val["Recall"]
    + 0.15 * results_val["ROC_AUC"]
)

results_val = results_val.sort_values(
    "Selection_Score",
    ascending=False
)

display(results_val)

best_name = results_val.iloc[0]["Model"]
best_model = fitted_models[best_name]

print("Meilleur modèle :", best_name)

"""## 25. Optimisation du seuil de décision"""

val_probability = best_model.predict_proba(
    X_val
)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(
    y_val,
    val_probability
)

f1_values = (
    2 * precisions * recalls /
    (precisions + recalls + 1e-12)
)

eligible = np.where(
    recalls[:-1] >= 0.85
)[0]

if len(eligible) > 0:
    best_threshold_idx = eligible[
        np.argmax(f1_values[eligible])
    ]
else:
    best_threshold_idx = np.nanargmax(
        f1_values[:-1]
    )

BEST_THRESHOLD = float(
    thresholds[best_threshold_idx]
)

print("Seuil :", round(BEST_THRESHOLD, 4))
print(
    "Precision validation :",
    round(float(precisions[best_threshold_idx]), 4)
)
print(
    "Recall validation :",
    round(float(recalls[best_threshold_idx]), 4)
)
print(
    "F1 validation :",
    round(float(f1_values[best_threshold_idx]), 4)
)

"""## 26. Évaluation finale du meilleur modèle"""

test_probability = best_model.predict_proba(
    X_test
)[:, 1]

test_prediction = (
    test_probability >= BEST_THRESHOLD
).astype(int)

final_metrics = pd.DataFrame([{
    "Model": best_name,
    "Threshold": BEST_THRESHOLD,
    "Accuracy": accuracy_score(
        y_test, test_prediction
    ),
    "Precision": precision_score(
        y_test, test_prediction, zero_division=0
    ),
    "Recall": recall_score(
        y_test, test_prediction, zero_division=0
    ),
    "F1": f1_score(
        y_test, test_prediction, zero_division=0
    ),
    "ROC_AUC": roc_auc_score(
        y_test, test_probability
    ),
    "PR_AUC": average_precision_score(
        y_test, test_probability
    )
}])

display(final_metrics)

print(
    classification_report(
        y_test,
        test_prediction,
        target_names=[
            "Normal",
            "Panne < 4h"
        ]
    )
)

"""## 27. Matrice de confusion"""

fig, ax = plt.subplots(figsize=(6, 5))

ConfusionMatrixDisplay.from_predictions(
    y_test,
    test_prediction,
    display_labels=[
        "Normal",
        "Panne < 4h"
    ],
    values_format="d",
    ax=ax
)

ax.set_title(
    f"Matrice de confusion — {best_name}"
)

plt.tight_layout()
plt.show()

"""## 28. Courbe ROC / AUC"""

fpr, tpr, _ = roc_curve(
    y_test,
    test_probability
)

auc_value = roc_auc_score(
    y_test,
    test_probability
)

fig, ax = plt.subplots(figsize=(7, 5))

ax.plot(
    fpr,
    tpr,
    label=f"{best_name} — AUC={auc_value:.4f}"
)

ax.plot(
    [0, 1],
    [0, 1],
    linestyle="--"
)

ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_title("Courbe ROC")
ax.legend()

plt.tight_layout()
plt.show()

"""## 29. Courbe Precision-Recall"""

precision_pr, recall_pr, _ = precision_recall_curve(
    y_test,
    test_probability
)

pr_auc_value = average_precision_score(
    y_test,
    test_probability
)

fig, ax = plt.subplots(figsize=(7, 5))

ax.plot(
    recall_pr,
    precision_pr,
    label=f"PR-AUC={pr_auc_value:.4f}"
)

ax.set_xlabel("Recall")
ax.set_ylabel("Precision")
ax.set_title("Courbe Precision-Recall")
ax.legend()

plt.tight_layout()
plt.show()

"""## 30. Comparaison graphique des performances"""

plot_df = results_val.sort_values(
    "F1",
    ascending=True
)

fig, ax = plt.subplots(figsize=(10, 6))

positions = np.arange(len(plot_df))

ax.barh(
    positions,
    plot_df["F1"]
)

ax.set_yticks(positions)
ax.set_yticklabels(plot_df["Model"])
ax.set_xlabel("F1-Score")
ax.set_title("Comparaison des modèles")

plt.tight_layout()
plt.show()

"""## 31. Importance des variables"""

TREE_MODEL_NAMES = {
    "Decision Tree",
    "Random Forest",
    "XGBoost",
    "LightGBM",
    "Decision Tree Tuned",
    "Random Forest Tuned"
}

if best_name in TREE_MODEL_NAMES:
    importance_model_name = best_name
else:
    importance_model_name = (
        results_val[
            results_val["Model"].isin(
                TREE_MODEL_NAMES
            )
        ]
        .sort_values("F1", ascending=False)
        .iloc[0]["Model"]
    )

importance_pipeline = fitted_models[
    importance_model_name
]

fitted_preprocessor = (
    importance_pipeline
    .named_steps["preprocessor"]
)

tree_estimator = (
    importance_pipeline
    .named_steps["model"]
)

feature_names = (
    fitted_preprocessor
    .get_feature_names_out()
)

importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": tree_estimator.feature_importances_
}).sort_values(
    "importance",
    ascending=False
)

display(importance_df.head(25))

top_imp = (
    importance_df
    .head(20)
    .sort_values("importance")
)

fig, ax = plt.subplots(figsize=(9, 7))

ax.barh(
    top_imp["feature"],
    top_imp["importance"]
)

ax.set_title(
    f"Importance des variables — {importance_model_name}"
)

plt.tight_layout()
plt.show()

"""## 32. Modèle secondaire — prédiction du type de panne"""

positive_train_mask = (
    y_train.to_numpy() == 1
)

positive_test_mask = (
    y_test.to_numpy() == 1
)

type_model = Pipeline([
    ("preprocessor", clone(preprocessor)),
    (
        "model",
        RandomForestClassifier(
            n_estimators=260,
            max_depth=18,
            class_weight="balanced_subsample",
            n_jobs=-1,
            random_state=RANDOM_STATE
        )
    )
])

type_model.fit(
    X_train.iloc[
        np.where(positive_train_mask)[0]
    ],
    type_train.iloc[
        np.where(positive_train_mask)[0]
    ]
)

if positive_test_mask.sum() > 0:
    type_prediction = type_model.predict(
        X_test.iloc[
            np.where(positive_test_mask)[0]
        ]
    )

    print(
        classification_report(
            type_test.iloc[
                np.where(positive_test_mask)[0]
            ],
            type_prediction
        )
    )

"""## 33. IA Explicable — SHAP"""

import shap

xai_pipeline = importance_pipeline
xai_preprocessor = (
    xai_pipeline
    .named_steps["preprocessor"]
)
xai_estimator = (
    xai_pipeline
    .named_steps["model"]
)

shap_sample_size = min(
    800,
    len(X_test)
)

shap_indices = (
    np.random.RandomState(RANDOM_STATE)
    .choice(
        len(X_test),
        shap_sample_size,
        replace=False
    )
)

X_shap_raw = X_test.iloc[
    shap_indices
]

X_shap = xai_preprocessor.transform(
    X_shap_raw
)

xai_feature_names = (
    xai_preprocessor
    .get_feature_names_out()
)

shap_explainer = shap.TreeExplainer(
    xai_estimator
)

shap_values = shap_explainer.shap_values(
    X_shap
)

if isinstance(shap_values, list):
    shap_class1 = shap_values[1]
elif np.asarray(shap_values).ndim == 3:
    shap_class1 = np.asarray(
        shap_values
    )[:, :, 1]
else:
    shap_class1 = shap_values

shap.summary_plot(
    shap_class1,
    X_shap,
    feature_names=xai_feature_names,
    show=True
)

"""### SHAP — explication individuelle"""

sample_id = 0

print(
    "Probabilité prédite :",
    best_model.predict_proba(
        X_shap_raw.iloc[[sample_id]]
    )[0, 1]
)

base_value = shap_explainer.expected_value

if isinstance(base_value, (list, np.ndarray)):
    base_arr = np.asarray(base_value).reshape(-1)
    if len(base_arr) > 1:
        base_value = base_arr[-1]
    else:
        base_value = base_arr[0]

shap.force_plot(
    base_value,
    shap_class1[sample_id],
    X_shap[sample_id],
    feature_names=xai_feature_names,
    matplotlib=True
)

plt.show()

"""## 34. IA Explicable — LIME"""

from lime.lime_tabular import (
    LimeTabularExplainer
)

lime_train_size = min(
    10000,
    len(X_train)
)

lime_indices = (
    np.random.RandomState(RANDOM_STATE)
    .choice(
        len(X_train),
        lime_train_size,
        replace=False
    )
)

X_lime_train = xai_preprocessor.transform(
    X_train.iloc[lime_indices]
)

X_lime_test = xai_preprocessor.transform(
    X_test.iloc[:10]
)

lime_explainer = LimeTabularExplainer(
    training_data=np.asarray(
        X_lime_train
    ),
    feature_names=list(
        xai_feature_names
    ),
    class_names=[
        "Normal",
        "Panne < 4h"
    ],
    mode="classification",
    discretize_continuous=True,
    random_state=RANDOM_STATE
)

lime_explanation = (
    lime_explainer
    .explain_instance(
        np.asarray(
            X_lime_test
        )[0],
        xai_estimator.predict_proba,
        num_features=12
    )
)

print(
    lime_explanation.as_list()
)

fig = (
    lime_explanation
    .as_pyplot_figure()
)

plt.tight_layout()
plt.show()

"""## 35. Détection d'anomalies — Isolation Forest"""

anomaly_features = [
    "temperature_c",
    "pressure_hpa",
    "vibration_x_ms2",
    "vibration_y_ms2",
    "vibration_z_ms2",
    "vibration_norm_ms2",
    "voltage_v",
    "current_a",
    "power_w",
    "load_pct",
    "rpm"
]

anomaly_preprocessor = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="median")
    ),
    (
        "scaler",
        StandardScaler()
    )
])

X_anomaly_train = (
    anomaly_preprocessor
    .fit_transform(
        df_fe.iloc[
            train_idx
        ][anomaly_features]
    )
)

X_anomaly_test = (
    anomaly_preprocessor
    .transform(
        df_fe.iloc[
            test_idx
        ][anomaly_features]
    )
)

isolation_forest = IsolationForest(
    n_estimators=250,
    contamination=0.08,
    n_jobs=-1,
    random_state=RANDOM_STATE
)

isolation_forest.fit(
    X_anomaly_train
)

iso_prediction = (
    isolation_forest.predict(
        X_anomaly_test
    ) == -1
).astype(int)

anomaly_true = (
    df_fe.iloc[
        test_idx
    ]["anomaly_reference"]
    .astype(int)
    .to_numpy()
)

print("Isolation Forest")
print(
    classification_report(
        anomaly_true,
        iso_prediction,
        target_names=[
            "Normal",
            "Anomalie"
        ]
    )
)

"""## 36. Détection d'anomalies — Local Outlier Factor"""

lof_train_size = min(
    35000,
    len(X_anomaly_train)
)

lof_indices = (
    np.random.RandomState(RANDOM_STATE)
    .choice(
        len(X_anomaly_train),
        lof_train_size,
        replace=False
    )
)

lof_model = LocalOutlierFactor(
    n_neighbors=35,
    contamination=0.08,
    novelty=True,
    n_jobs=-1
)

lof_model.fit(
    X_anomaly_train[
        lof_indices
    ]
)

lof_prediction = (
    lof_model.predict(
        X_anomaly_test
    ) == -1
).astype(int)

print("Local Outlier Factor")
print(
    classification_report(
        anomaly_true,
        lof_prediction,
        target_names=[
            "Normal",
            "Anomalie"
        ]
    )
)

"""## 37. Calcul d'un indice de risque"""

def risk_level(probability):
    risk = 100 * probability

    if risk < 30:
        return "Faible"
    elif risk < 60:
        return "Modéré"
    elif risk < 80:
        return "Élevé"
    else:
        return "Critique"

test_results = (
    df_fe.iloc[
        test_idx
    ][[
        "record_id",
        "equipment_id",
        "timestamp",
        "equipment_type",
        "flight_phase",
        "temperature_c",
        "pressure_hpa",
        "vibration_norm_ms2",
        "voltage_v",
        "current_a",
        "power_w"
    ]]
    .copy()
    .reset_index(drop=True)
)

test_results["failure_probability"] = (
    test_probability
)

test_results["risk_score_pct"] = (
    100 * test_probability
)

test_results["risk_level"] = [
    risk_level(p)
    for p in test_probability
]

test_results["predicted_failure"] = (
    test_prediction
)

display(
    test_results
    .sort_values(
        "risk_score_pct",
        ascending=False
    )
    .head(20)
)

"""## 38. Système d'alerte intelligent"""

healthy_train = (
    df_fe.iloc[
        train_idx
    ]
    .iloc[
        np.where(
            y_train.to_numpy() == 0
        )[0]
    ]
)

driver_cols = [
    "temperature_c",
    "pressure_hpa",
    "vibration_norm_ms2",
    "voltage_v",
    "current_a",
    "power_w"
]

healthy_mean = (
    healthy_train[
        driver_cols
    ]
    .mean()
)

healthy_std = (
    healthy_train[
        driver_cols
    ]
    .std()
    .replace(0, 1)
)

def identify_drivers(row, top_n=3):
    z = (
        (
            row[driver_cols]
            - healthy_mean
        )
        / healthy_std
    ).abs()

    return ", ".join(
        z.sort_values(
            ascending=False
        )
        .head(top_n)
        .index
        .tolist()
    )

predicted_types = np.full(
    len(X_test),
    "No_Failure",
    dtype=object
)

positive_prediction_idx = np.where(
    test_prediction == 1
)[0]

if len(positive_prediction_idx) > 0:
    predicted_types[
        positive_prediction_idx
    ] = type_model.predict(
        X_test.iloc[
            positive_prediction_idx
        ]
    )

test_results[
    "predicted_failure_type"
] = predicted_types

test_results[
    "risk_drivers"
] = test_results.apply(
    identify_drivers,
    axis=1
)

recommendations = {
    "Overheating":
        "Inspecter le refroidissement, la ventilation et les connexions thermiques.",

    "Pressure_Loss":
        "Contrôler l'étanchéité, les conduites et les raccords.",

    "Mechanical_Vibration":
        "Inspecter roulements, fixation, alignement et équilibrage.",

    "Electrical_Drift":
        "Contrôler alimentation, câblage, tension, courant et connecteurs.",

    "Combined_Fault":
        "Inspection multidisciplinaire immédiate de l'équipement.",

    "No_Failure":
        "Poursuivre la surveillance."
}

test_results[
    "maintenance_recommendation"
] = (
    test_results[
        "predicted_failure_type"
    ]
    .map(recommendations)
    .fillna(
        "Inspection de maintenance recommandée."
    )
)

alerts = test_results[
    (
        test_results[
            "risk_score_pct"
        ] >= 60
    )
    |
    (
        test_results[
            "predicted_failure"
        ] == 1
    )
].copy()

display(
    alerts
    .sort_values(
        "risk_score_pct",
        ascending=False
    )
    .head(30)
)

"""## 39. Sauvegarde du meilleur modèle et du pipeline"""

ARTIFACT_DIR = Path(
    "deployment_artifacts"
)

ARTIFACT_DIR.mkdir(
    exist_ok=True
)

joblib.dump(
    best_model,
    ARTIFACT_DIR /
    "best_failure_model.joblib"
)

joblib.dump(
    type_model,
    ARTIFACT_DIR /
    "failure_type_model.joblib"
)

joblib.dump(
    anomaly_preprocessor,
    ARTIFACT_DIR /
    "anomaly_preprocessor.joblib"
)

joblib.dump(
    isolation_forest,
    ARTIFACT_DIR /
    "isolation_forest.joblib"
)

joblib.dump(
    best_model.named_steps[
        "preprocessor"
    ],
    ARTIFACT_DIR /
    "preprocessor_scaler_encoders.joblib"
)

with open(
    ARTIFACT_DIR /
    "features_used.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        FEATURE_COLUMNS,
        f,
        ensure_ascii=False,
        indent=2
    )

metadata = {
    "project":
        "Aeronautical IoT Predictive Maintenance",

    "author":
        "Dr. ET-TOUSY Jamal",

    "academic_year":
        "2025/2026",

    "target":
        TARGET,

    "best_model":
        best_name,

    "threshold":
        BEST_THRESHOLD
}

with open(
    ARTIFACT_DIR /
    "model_metadata.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        metadata,
        f,
        ensure_ascii=False,
        indent=2
    )

alerts.to_csv(
    ARTIFACT_DIR /
    "alerts_test.csv",
    index=False
)

print(
    "Artefacts sauvegardés :",
    ARTIFACT_DIR.resolve()
)

"""## 40. Préparation du déploiement"""

ENGINEERED_COLUMNS = [
    "temp_delta_ambient",
    "thermal_load_index",
    "vibration_energy",
    "vibration_per_krpm",
    "voltage_deviation_v",
    "calculated_power_w",
    "power_sensor_error_w",
    "power_per_load",
    "pressure_ratio_atm",
    "maintenance_stress_index",
    "age_load_interaction",
    "hour_sin",
    "hour_cos"
]

RAW_MODEL_COLUMNS = [
    col for col in FEATURE_COLUMNS
    if col not in ENGINEERED_COLUMNS
]

deployment_defaults = {}

for col in RAW_MODEL_COLUMNS:
    if col in df_clean.columns:
        if pd.api.types.is_numeric_dtype(
            df_clean[col]
        ):
            deployment_defaults[col] = float(
                df_clean[col].median()
            )
        else:
            mode = (
                df_clean[col]
                .mode(dropna=True)
            )
            deployment_defaults[col] = (
                str(mode.iloc[0])
                if len(mode)
                else "UNKNOWN"
            )

with open(
    ARTIFACT_DIR /
    "deployment_defaults.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        deployment_defaults,
        f,
        ensure_ascii=False,
        indent=2
    )

print(
    "Valeurs par défaut prêtes."
)

"""## 41. Génération de l'application Streamlit"""

streamlit_code = r"""
import io
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import streamlit as st

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

ART = Path("deployment_artifacts")

model = joblib.load(
    ART / "best_failure_model.joblib"
)

type_model = joblib.load(
    ART / "failure_type_model.joblib"
)

with open(
    ART / "model_metadata.json",
    encoding="utf-8"
) as f:
    metadata = json.load(f)

with open(
    ART / "features_used.json",
    encoding="utf-8"
) as f:
    FEATURE_COLUMNS = json.load(f)

with open(
    ART / "deployment_defaults.json",
    encoding="utf-8"
) as f:
    defaults = json.load(f)

THRESHOLD = float(
    metadata["threshold"]
)

def add_engineered_features(data):
    d = data.copy()

    d["temp_delta_ambient"] = (
        d["temperature_c"]
        - d["ambient_temp_c"]
    )

    d["thermal_load_index"] = (
        d["temperature_c"]
        * d["load_pct"]
        / 100.0
    )

    d["vibration_energy"] = (
        d["vibration_norm_ms2"] ** 2
    )

    d["vibration_per_krpm"] = (
        1000
        * d["vibration_norm_ms2"]
        / (d["rpm"].abs() + 1.0)
    )

    d["voltage_deviation_v"] = (
        d["voltage_v"] - 28.0
    ).abs()

    d["calculated_power_w"] = (
        d["voltage_v"]
        * d["current_a"]
    )

    d["power_sensor_error_w"] = (
        d["power_w"]
        - d["calculated_power_w"]
    ).abs()

    d["power_per_load"] = (
        d["power_w"]
        / (d["load_pct"].abs() + 1.0)
    )

    d["pressure_ratio_atm"] = (
        d["pressure_hpa"]
        / (
            d["atmospheric_pressure_hpa"]
            .abs()
            + 1.0
        )
    )

    d["maintenance_stress_index"] = (
        d["load_pct"]
        * (
            1
            + d["maintenance_age_days"]
            / 180.0
        )
    )

    d["age_load_interaction"] = (
        np.log1p(
            d["operating_hours"]
            .clip(lower=0)
        )
        * d["load_pct"]
    )

    if "timestamp" in d.columns:
        ts = pd.to_datetime(
            d["timestamp"],
            errors="coerce"
        )
        ts = ts.fillna(
            pd.Timestamp.now()
        )
        hour = (
            ts.dt.hour
            + ts.dt.minute/60
        )
    else:
        hour = pd.Series(
            np.zeros(len(d)),
            index=d.index
        )

    d["hour_sin"] = np.sin(
        2*np.pi*hour/24
    )
    d["hour_cos"] = np.cos(
        2*np.pi*hour/24
    )

    return d

def risk_level(probability):
    pct = 100*probability

    if pct < 30:
        return "Faible"
    if pct < 60:
        return "Modéré"
    if pct < 80:
        return "Élevé"

    return "Critique"

recommendations = {
    "Overheating":
        "Inspecter le refroidissement et la ventilation.",

    "Pressure_Loss":
        "Contrôler l'étanchéité, les conduites et les raccords.",

    "Mechanical_Vibration":
        "Inspecter roulements, fixation et équilibrage.",

    "Electrical_Drift":
        "Contrôler alimentation, câblage, tension et courant.",

    "Combined_Fault":
        "Inspection multidisciplinaire immédiate.",

    "No_Failure":
        "Poursuivre la surveillance."
}

def predict_frame(raw_df):
    d = raw_df.copy()

    if "timestamp" not in d.columns:
        d["timestamp"] = pd.Timestamp.now()

    d = add_engineered_features(d)

    for col in FEATURE_COLUMNS:
        if col not in d.columns:
            d[col] = np.nan

    X = d[FEATURE_COLUMNS]

    probability = model.predict_proba(
        X
    )[:, 1]

    prediction = (
        probability >= THRESHOLD
    ).astype(int)

    failure_type = np.full(
        len(d),
        "No_Failure",
        dtype=object
    )

    idx = np.where(
        prediction == 1
    )[0]

    if len(idx):
        failure_type[idx] = (
            type_model.predict(
                X.iloc[idx]
            )
        )

    result = d.copy()

    result[
        "failure_probability"
    ] = probability

    result[
        "risk_score_pct"
    ] = 100*probability

    result[
        "risk_level"
    ] = [
        risk_level(p)
        for p in probability
    ]

    result[
        "predicted_failure"
    ] = prediction

    result[
        "predicted_failure_type"
    ] = failure_type

    result[
        "maintenance_recommendation"
    ] = [
        recommendations.get(
            ft,
            "Inspection recommandée."
        )
        for ft in failure_type
    ]

    return result

def make_pdf(row):
    buffer = io.BytesIO()

    pdf = canvas.Canvas(
        buffer,
        pagesize=A4
    )

    _, height = A4
    y = height - 50

    pdf.setFont(
        "Helvetica-Bold",
        14
    )

    pdf.drawString(
        45,
        y,
        "Rapport de prediction - Maintenance aeronautique"
    )

    y -= 25

    pdf.setFont(
        "Helvetica",
        10
    )

    pdf.drawString(
        45,
        y,
        "Realise par : Dr. ET-TOUSY Jamal | AU : 2025/2026"
    )

    y -= 30

    fields = [
        (
            "Equipement",
            str(
                row.get(
                    "equipment_id",
                    "N/A"
                )
            )
        ),
        (
            "Probabilite de panne",
            f"{100*float(row['failure_probability']):.2f}%"
        ),
        (
            "Niveau de risque",
            str(row["risk_level"])
        ),
        (
            "Type de panne",
            str(
                row[
                    "predicted_failure_type"
                ]
            )
        ),
        (
            "Temperature",
            f"{float(row.get('temperature_c', np.nan)):.2f} C"
        ),
        (
            "Pression",
            f"{float(row.get('pressure_hpa', np.nan)):.2f} hPa"
        ),
        (
            "Vibration",
            f"{float(row.get('vibration_norm_ms2', np.nan)):.3f} m/s2"
        ),
        (
            "Tension",
            f"{float(row.get('voltage_v', np.nan)):.2f} V"
        ),
        (
            "Courant",
            f"{float(row.get('current_a', np.nan)):.2f} A"
        ),
        (
            "Recommandation",
            str(
                row[
                    "maintenance_recommendation"
                ]
            )
        )
    ]

    for label, value in fields:
        pdf.setFont(
            "Helvetica-Bold",
            10
        )
        pdf.drawString(
            45,
            y,
            label + " :"
        )

        pdf.setFont(
            "Helvetica",
            10
        )
        pdf.drawString(
            180,
            y,
            value[:90]
        )

        y -= 20

    pdf.save()
    buffer.seek(0)

    return buffer

st.set_page_config(
    page_title="Aeronautical IoT Predictive Maintenance",
    layout="wide"
)

st.title(
    "✈️ Aeronautical IoT Predictive Maintenance"
)

st.caption(
    "Réalisé par : Dr. ET-TOUSY Jamal — AU : 2025/2026"
)

mode = st.sidebar.radio(
    "Mode",
    [
        "Saisie manuelle",
        "Importer un CSV"
    ]
)

if mode == "Saisie manuelle":
    row = dict(defaults)
    row["timestamp"] = pd.Timestamp.now()

    c1, c2 = st.columns(2)

    with c1:
        row["temperature_c"] = st.number_input(
            "Température (°C)",
            value=float(
                defaults.get(
                    "temperature_c",
                    65.0
                )
            )
        )

        row["pressure_hpa"] = st.number_input(
            "Pression process (hPa)",
            value=float(
                defaults.get(
                    "pressure_hpa",
                    1500.0
                )
            )
        )

        row["vibration_x_ms2"] = st.number_input(
            "Vibration X (m/s²)",
            value=float(
                defaults.get(
                    "vibration_x_ms2",
                    1.0
                )
            )
        )

        row["vibration_y_ms2"] = st.number_input(
            "Vibration Y (m/s²)",
            value=float(
                defaults.get(
                    "vibration_y_ms2",
                    1.0
                )
            )
        )

        row["vibration_z_ms2"] = st.number_input(
            "Vibration Z (m/s²)",
            value=float(
                defaults.get(
                    "vibration_z_ms2",
                    1.0
                )
            )
        )

    with c2:
        row["voltage_v"] = st.number_input(
            "Tension (V)",
            value=float(
                defaults.get(
                    "voltage_v",
                    28.0
                )
            )
        )

        row["current_a"] = st.number_input(
            "Courant (A)",
            value=float(
                defaults.get(
                    "current_a",
                    20.0
                )
            )
        )

        row["load_pct"] = st.slider(
            "Charge (%)",
            0.0,
            120.0,
            float(
                min(
                    defaults.get(
                        "load_pct",
                        60.0
                    ),
                    120.0
                )
            )
        )

        row["maintenance_age_days"] = st.number_input(
            "Jours depuis maintenance",
            value=float(
                defaults.get(
                    "maintenance_age_days",
                    60.0
                )
            )
        )

    row["vibration_norm_ms2"] = float(
        np.sqrt(
            row["vibration_x_ms2"]**2
            + row["vibration_y_ms2"]**2
            + row["vibration_z_ms2"]**2
        )
    )

    row["power_w"] = (
        row["voltage_v"]
        * row["current_a"]
    )

    row["energy_wh_interval"] = (
        row["power_w"]
        * (5/60)
    )

    if st.button(
        "Analyser l'équipement",
        type="primary"
    ):
        result = predict_frame(
            pd.DataFrame([row])
        )

        r = result.iloc[0]

        k1, k2, k3, k4 = st.columns(4)

        k1.metric(
            "Probabilité",
            f"{100*r['failure_probability']:.1f}%"
        )

        k2.metric(
            "Risque",
            r["risk_level"]
        )

        k3.metric(
            "Type",
            r["predicted_failure_type"]
        )

        k4.metric(
            "Vibration",
            f"{r['vibration_norm_ms2']:.2f} m/s²"
        )

        st.progress(
            min(
                float(
                    r["failure_probability"]
                ),
                1.0
            )
        )

        st.info(
            r[
                "maintenance_recommendation"
            ]
        )

        chart_values = pd.Series({
            "Température":
                r["temperature_c"],

            "Vibration":
                r["vibration_norm_ms2"],

            "Tension":
                r["voltage_v"],

            "Courant":
                r["current_a"]
        })

        st.bar_chart(
            chart_values
        )

        pdf_buffer = make_pdf(r)

        st.download_button(
            "Télécharger le rapport PDF",
            data=pdf_buffer,
            file_name="rapport_prediction_aeronautique.pdf",
            mime="application/pdf"
        )

else:
    uploaded = st.file_uploader(
        "Importer un CSV",
        type=["csv"]
    )

    if uploaded is not None:
        incoming = pd.read_csv(
            uploaded
        )

        results = predict_frame(
            incoming
        )

        st.metric(
            "Lignes analysées",
            len(results)
        )

        st.metric(
            "Risques ≥ 60%",
            int(
                (
                    results[
                        "risk_score_pct"
                    ] >= 60
                ).sum()
            )
        )

        st.dataframe(
            results.sort_values(
                "risk_score_pct",
                ascending=False
            ),
            use_container_width=True
        )

        if "timestamp" in results.columns:
            tmp = results.copy()

            tmp["timestamp"] = pd.to_datetime(
                tmp["timestamp"],
                errors="coerce"
            )

            tmp = (
                tmp
                .dropna(
                    subset=["timestamp"]
                )
                .sort_values(
                    "timestamp"
                )
            )

            if len(tmp):
                st.line_chart(
                    tmp.set_index(
                        "timestamp"
                    )[
                        "risk_score_pct"
                    ]
                )

        st.download_button(
            "Télécharger les prédictions CSV",
            data=results.to_csv(
                index=False
            ).encode("utf-8"),
            file_name="predictions_aeronautiques.csv",
            mime="text/csv"
        )
"""

Path(
    "streamlit_app.py"
).write_text(
    streamlit_code,
    encoding="utf-8"
)

print(
    "streamlit_app.py généré."
)

"""## 42. Génération automatique d'un rapport PDF"""

report_code = r"""
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

def generate_prediction_report(
    row,
    output_path="prediction_report.pdf"
):
    pdf = canvas.Canvas(
        output_path,
        pagesize=A4
    )

    _, height = A4
    y = height - 50

    pdf.setFont(
        "Helvetica-Bold",
        15
    )

    pdf.drawString(
        45,
        y,
        "Rapport de maintenance predictive aeronautique"
    )

    y -= 25

    pdf.setFont(
        "Helvetica",
        10
    )

    pdf.drawString(
        45,
        y,
        "Realise par : Dr. ET-TOUSY Jamal | AU : 2025/2026"
    )

    y -= 30

    entries = [
        (
            "Equipment",
            row.get(
                "equipment_id",
                "N/A"
            )
        ),
        (
            "Failure probability",
            f"{row.get('risk_score_pct', 0):.2f}%"
        ),
        (
            "Risk level",
            row.get(
                "risk_level",
                "N/A"
            )
        ),
        (
            "Predicted failure type",
            row.get(
                "predicted_failure_type",
                "N/A"
            )
        ),
        (
            "Risk drivers",
            row.get(
                "risk_drivers",
                "N/A"
            )
        ),
        (
            "Maintenance recommendation",
            row.get(
                "maintenance_recommendation",
                "N/A"
            )
        )
    ]

    for label, value in entries:
        pdf.setFont(
            "Helvetica-Bold",
            10
        )
        pdf.drawString(
            45,
            y,
            str(label) + " :"
        )

        pdf.setFont(
            "Helvetica",
            10
        )
        pdf.drawString(
            195,
            y,
            str(value)[:95]
        )

        y -= 20

    pdf.save()

    return output_path
"""

Path(
    "report_generator.py"
).write_text(
    report_code,
    encoding="utf-8"
)

print(
    "report_generator.py généré."
)

"""## 43. Fichier requirements.txt"""

requirements_text = """pandas
numpy
matplotlib
scikit-learn
imbalanced-learn
xgboost
lightgbm
shap
lime
joblib
streamlit
reportlab
"""

Path(
    "requirements.txt"
).write_text(
    requirements_text,
    encoding="utf-8"
)

print(
    requirements_text
)

"""## 44. GitHub et Streamlit Community Cloud"""

readme_text = """# Aeronautical IoT Predictive Maintenance

Réalisé par : Dr. ET-TOUSY Jamal
AU : 2025/2026

## Installation
```bash
pip install -r requirements.txt
```

## Entraînement
Exécuter le notebook puis récupérer le dossier `deployment_artifacts`.

## Streamlit
```bash
streamlit run streamlit_app.py
```

## Déploiement
1. Créer un repository GitHub.
2. Ajouter `streamlit_app.py`, `requirements.txt` et `deployment_artifacts/`.
3. Pousser le projet.
4. Ouvrir Streamlit Community Cloud.
5. Sélectionner le repository.
6. Choisir `streamlit_app.py`.
7. Déployer.

## Note
Dataset synthétique destiné à l'apprentissage et au prototypage.
"""

Path(
    "README.md"
).write_text(
    readme_text,
    encoding="utf-8"
)

print(
    "README.md généré."
)